/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8AzhruA6Jux
 */
import { CardTitle, CardDescription, CardContent, Card } from "@/components/ui/card"
import Link from "next/link"

export function Branches() {
  return (
    <div className="grid max-w-3xl mt-10 gap-4 px-4 mx-auto sm:grid-cols-2 lg:gap-6 lg:px-6">
      <div className="space-y-2">
        <h1 className="text-3xl font-bold tracking-tighter">Branches</h1>
      </div>
      <div className="grid gap-4 sm:gap-6">
        <Link href={"/Branches/CSE"}>
        <Card>
          <CardContent className="flex flex-col py-5 gap-1">
            <CardTitle>Computer Science</CardTitle>
            <CardDescription>The study of algorithmic processes and data structures.</CardDescription>
          </CardContent>
        </Card>
        </Link>
        <Card>
          <CardContent className="flex flex-col py-5 gap-1">
            <CardTitle>Electrical Engineering</CardTitle>
            <CardDescription>The study of electrical systems and electronics.</CardDescription>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex flex-col py-5 gap-1">
            <CardTitle>Mechanical Engineering</CardTitle>
            <CardDescription>The study of machines, materials, and thermodynamics.</CardDescription>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex flex-col py-5 gap-1">
            <CardTitle>Civil Engineering</CardTitle>
            <CardDescription>The study of infrastructure and environmental systems.</CardDescription>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex flex-col py-5 gap-1">
            <CardTitle>Electronics and Communications Engineering</CardTitle>
            <CardDescription>The study of Communication processes and Electronics.</CardDescription>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
