/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HbPtwS6mqzg
 */
import { CardFooter } from "@/components/ui/card"
import Link from "next/link"

export function Semester({ Branch }:{Branch:string}) {
  return (
    <div className="grid items-center justify-center gap-8 md:grid-cols-2 lg:grid-cols-4">
      <div className="flex flex-col w-full max-w-sm p-4">
        <Link
          className="flex flex-1 group flex-col rounded-lg border border-gray-200 p-4 group transition duration-300 dark:border-gray-800"
          href={`/Branches/${Branch}/1`}
        >
          <div className="flex-1 group grid aspect-16x9 items-center justify-center text-center">
            <span className="text-3xl font-semibold">I</span>
          </div>
          <CardFooter className="p-4 flex justify-between">
            <span className="text-sm font-medium">First Semester</span>
            <ChevronRightIcon className="w-5 h-5 group-hover:translate-x-3 transition duration-200" />
          </CardFooter>
        </Link>
      </div>
      <div className="flex flex-col w-full max-w-sm p-4">
        <Link
          className="flex flex-1 group flex-col rounded-lg border border-gray-200 p-4 hover:shadow-lg transition duration-300 dark:border-gray-800"
          href={`/Branches/${Branch}/2`}
        >
          <div className="flex-1 group grid aspect-16x9 items-center justify-center text-center">
            <span className="text-3xl font-semibold">II</span>
          </div>
          <CardFooter className="p-4 flex justify-between">
            <span className="text-sm font-medium">Second Semester</span>
            <ChevronRightIcon className="w-5 h-5 group-hover:translate-x-3 transition duration-200" />
          </CardFooter>
        </Link>
      </div>
      <div className="flex flex-col w-full max-w-sm p-4">
        <Link
          className="flex flex-1 group flex-col rounded-lg border border-gray-200 p-4 hover:shadow-lg transition duration-300 dark:border-gray-800"
          href={`/Branches/${Branch}/3`}
        >
          <div className="flex-1 group grid aspect-16x9 items-center justify-center text-center">
            <span className="text-3xl font-semibold">III</span>
          </div>
          <CardFooter className="p-4 flex justify-between">
            <span className="text-sm font-medium">Third Semester</span>
            <ChevronRightIcon className="w-5 h-5 group-hover:translate-x-3 transition duration-200" />
          </CardFooter>
        </Link>
      </div>
      <div className="flex flex-col w-full max-w-sm p-4">
        <Link
          className="flex flex-1 group flex-col rounded-lg border border-gray-200 p-4 hover:shadow-lg transition duration-300 dark:border-gray-800"
          href={`/Branches/${Branch}/4`}
        >
          <div className="flex-1 grid aspect-16x9 items-center justify-center text-center">
            <span className="text-3xl font-semibold">IV</span>
          </div>
          <CardFooter className="p-4 flex justify-between">
            <span className="text-sm font-medium">Fourth Semester</span>
            <ChevronRightIcon className="w-5 h-5 group-hover:translate-x-3 transition duration-200" />
          </CardFooter>
        </Link>
      </div>
      <div className="flex flex-col w-full max-w-sm p-4">
        <Link
          className="flex flex-1 group flex-col rounded-lg border border-gray-200 p-4 hover:shadow-lg transition duration-300 dark:border-gray-800"
          href={`/Branches/${Branch}/5`}
        >
          <div className="flex-1 group grid aspect-16x9 items-center justify-center text-center">
            <span className="text-3xl font-semibold">V</span>
          </div>
          <CardFooter className="p-4 flex justify-between">
            <span className="text-sm font-medium">Fifth Semester</span>
            <ChevronRightIcon className="w-5 h-5 group-hover:translate-x-3 transition duration-200" />
          </CardFooter>
        </Link>
      </div>
      <div className="flex flex-col w-full max-w-sm p-4">
        <Link
          className="flex flex-1 group flex-col rounded-lg border border-gray-200 p-4 hover:shadow-lg transition duration-300 dark:border-gray-800"
          href={`/Branches/${Branch}/6`}
        >
          <div className="flex-1 group grid aspect-16x9 items-center justify-center text-center">
            <span className="text-3xl font-semibold">VI</span>
          </div>
          <CardFooter className="p-4 flex justify-between">
            <span className="text-sm font-medium">Sixth Semester</span>
            <ChevronRightIcon className="w-5 h-5 group-hover:translate-x-3 transition duration-200" />
          </CardFooter>
        </Link>
      </div>
      <div className="flex flex-col w-full max-w-sm p-4">
        <Link
          className="flex flex-1 group flex-col rounded-lg border border-gray-200 p-4 hover:shadow-lg transition duration-300 dark:border-gray-800"
          href={`/Branches/${Branch}/7`}
        >
          <div className="flex-1 group grid aspect-16x9 items-center justify-center text-center">
            <span className="text-3xl font-semibold">VII</span>
          </div>
          <CardFooter className="p-4 flex justify-between">
            <span className="text-sm font-medium">Seventh Semester</span>
            <ChevronRightIcon className="w-5 h-5 group-hover:translate-x-3 transition duration-200" />
          </CardFooter>
        </Link>
      </div>
      <div className="flex flex-col w-full max-w-sm p-4">
        <Link
          className="flex flex-1 group flex-col rounded-lg border border-gray-200 p-4 hover:shadow-lg transition duration-300 dark:border-gray-800"
          href={`/Branches/${Branch}/8`}
        >
          <div className="flex-1 group grid aspect-16x9 items-center justify-center text-center">
            <span className="text-3xl font-semibold">VIII</span>
          </div>
          <CardFooter className="p-4 flex justify-between">
            <span className="text-sm font-medium">Eighth Semester</span>
            <ChevronRightIcon className="w-5 h-5 group-hover:translate-x-3 transition duration-200" />
          </CardFooter>
        </Link>
      </div>
    </div>
  )
}


function ChevronRightIcon(props:{className:string}) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
