/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xoGafr3HH2S
 */
import { CardContent, Card } from "@/components/ui/card";
import PDF from "../ui/pdf";


export function Subjects() {
  return (
    <div key="1" className="bg-black text-white">
      <h2 className="text-3xl font-bold p-4">Operating Systems</h2>
      <div
        className="flex overflow-x-auto mb-16 p-4 space-x-4"
        style={{
          scrollbarColor: "white black",
          scrollbarWidth: "thin",
        }}
      >
       <PDF subject="Operating Systems" year={2023} className="w-[400px] aspect-[3/2]" />
        {/* <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Operating Systems Paper 2019</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Operating Systems Paper 2020</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Operating Systems Paper 2021</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Operating Systems Paper 2022</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Operating Systems Paper 2023</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Operating Systems Paper 2023</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Operating Systems Paper 2023</p>
          </CardContent>
        </Card> */}
      </div>
      <h2 className="text-3xl font-bold p-4">Machine Learning</h2>
      <div
        className="flex overflow-x-auto mb-16 p-4 space-x-4"
        style={{
          scrollbarColor: "white black",
          scrollbarWidth: "thin",
        }}
      >
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 1</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 2</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 3</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 4</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 5</p>
          </CardContent>
        </Card>
      </div>
      <h2 className="text-3xl font-bold p-4">Computer Graphics</h2>
      <div
        className="flex overflow-x-auto mb-16 p-4 space-x-4"
        style={{
          scrollbarColor: "white black",
          scrollbarWidth: "thin",
        }}
      >
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 6</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 7</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 8</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 9</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 10</p>
          </CardContent>
        </Card>
      </div>
      <h2 className="text-3xl font-bold p-4">Computer Networks</h2>
      <div
        className="flex overflow-x-auto mb-16 p-4 space-x-4"
        style={{
          scrollbarColor: "white black",
          scrollbarWidth: "thin",
        }}
      >
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 1</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 2</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 3</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 4</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 5</p>
          </CardContent>
        </Card>
      </div>
      <h2 className="text-3xl font-bold p-4">Software Engineering</h2>
      <div
        className="flex overflow-x-auto mb-16 p-4 space-x-4"
        style={{
          scrollbarColor: "white black",
          scrollbarWidth: "thin",
        }}
      >
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 6</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 7</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 8</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 9</p>
          </CardContent>
        </Card>
        <Card className="min-w-[250px] h-[140px]">
          <CardContent>
            <p>Subject 10</p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
